WIDTH="1920"             # Monitor Width
HEIGHT="1080"            # Monitor Height
REFRESHRATE="60"         # Monitor refresh rate
ADAPTATIVESYNC="FALSE"   # Choose either true or false(YOUR MONITOR NEEDS TO SUPPORT ADAPTATIVE SYNC).
